# Popes that have offsprings

SELECT
?popeItem ?pope ?image ?startTime ?endTime ?ordinal ?childItem ?child
WHERE {
  ?popeItem p:P39 ?positionStatement ;
            wdt:P40 ?childItem .
  ?positionStatement ps:P39 wd:Q19546 . # pope
  OPTIONAL { ?popeItem wdt:P18 ?image . }
  OPTIONAL { ?positionStatement pq:P580 ?startTime . }
  OPTIONAL { ?positionStatement pq:P582 ?endTime . }
  OPTIONAL { ?positionStatement pq:P1545 ?ordinal . }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". 
                           ?popeItem rdfs:label ?pope . 
                           ?childItem rdfs:label ?child . }
}
ORDER BY xsd:integer(?ordinal)
