# Dimensionless quantities in fluid mechanics that involving viscosity

SELECT
?quantityItem ?quantity ?formula ?namedAfter
WHERE {
  ?quantityItem (wdt:P31|wdt:P279)* wd:Q9051300 ; # dimensionless number
              wdt:P527 [ wdt:P279* wd:Q128709 ] . # viscosity
  OPTIONAL { ?quantityItem wdt:P2534 ?formula . }
  OPTIONAL { ?quantityItem wdt:P138 ?namedAfterItem . }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en".
                           ?quantityItem rdfs:label ?quantity .
                           ?namedAfterItem rdfs:label ?namedAfter . }
}
